### ISSUE TITLE
Report of Multiple OpenMP Runtime Instances Linked in Software Installation on Windows 10

### ISSUE THREAD

**Issue by jeginderof** [SBU-BMI/wsinfer#212] opened 2024-02-06 06:58 UTC
(base) C:\>wsinfer  --help
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

(base) C:\>

**Comment by kaczmarj** [comment] 2024-02-06 12:39
Thanks for the report. Could you please provide the following information to help us track down the issue?- your operating system and version- how did you install wsinfer?- which version of wsinfer are you using?- which version of PyTorch are you using?- how did you install PyTorch?I’m wondering which of our dependencies use openmp. They could include PyTorch, numpy, and shapely.On Feb 6, 2024, at 02:58, jeginderof ***@***.***> wrote:﻿
(base) C:>wsinfer  --help
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
(base) C:>

**Comment by jeginderof** [comment] 2024-02-06 14:13
I tried to update:

`python -m pip install git+https://github.com/SBU-BMI/wsinfer`

but still issue persists:

```
Uninstalling wsinfer-0.5.0:
      Successfully uninstalled wsinfer-0.5.0
Successfully installed wsinfer-0.5.1.dev5+gd28caf1
PS C:\Users\pqmao> wsinfer --help
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it c
an degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked
 into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented
 workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that
 may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/product
s/support/.
```

**Comment by kaczmarj** [comment] 2024-02-06 22:06
Thanks. Let me debug this and see where the issue is coming from. Please ping me here if you don’t here from me in a few days. On Feb 6, 2024, at 10:13, jeginderof ***@***.***> wrote:﻿
I tried to update:
python -m pip install git+https://github.com/SBU-BMI/wsinfer
but still issue persists:
Uninstalling wsinfer-0.5.0:
      Successfully uninstalled wsinfer-0.5.0
Successfully installed wsinfer-0.5.1.dev5+gd28caf1
PS C:\Users\pqmao> wsinfer --help
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it c
an degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked
 into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented
 workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that
 may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/product
s/support/.

**Comment by kaczmarj** [comment] 2024-02-07 22:18
@jeginderof - can you please try creating a new virtual environment for wsinfer? using something like venv in the standard library.

**Comment by jeginderof** [comment] 2024-02-08 11:07
Thank you, Now it works

```
wsinfer --help
Usage: wsinfer [OPTIONS] COMMAND [ARGS]...

  Run patch-level classification inference on whole slide images.

Options:
  --backend [openslide|tiffslide]
                                  Backend for loading whole slide images.
  --log-level [debug|info|warning|error|critical]
                                  Set the loudness of logging.
  --version                       Show the version and exit.
  --help                          Show this message and exit.

Commands:
  patch  Patch a directory of whole slide iamges.
  run    Run model inference on a directory of whole slide images.
  tosbu  Convert model outputs to Stony Brook format.

```

**Comment by kaczmarj** [comment] 2024-02-08 16:04
excellent, glad this worked. closing the issue now.

**Closed by kaczmarj** 2024-02-08 16:04 UTC
